### ISSUE TITLE
Issue installing the package whit "python setup.py install". How can I replace the missed library? 

### ISSUE THREAD

**Issue by martinBmeza** [jfsantos/SRMRpy#10]
No local packages or working download links found for Gammatone@ https://github.com/detly/gammatone/archive/master.zip#egg=Gammatone
error: Could not find suitable distribution for Requirement.parse('Gammatone@ https://github.com/detly/gammatone/archive/master.zip#egg=Gammatone')

**Comment by jfsantos** [comment]
You can clone the gammatone repository and install it separately first, then install SRMRpy. Let me know if it works.

**Comment by martinBmeza** [comment]
It works perfectly. Thanks! 👍🏿
