### ISSUE TITLE
Gammatone module not found

### ISSUE THREAD

**Issue by gautambhat14** [jfsantos/SRMRpy#3]
I am getting an error saying the Gammatone module is not present. I checked the package and the Gammatone module is not there. Can you please resolve this?

**Comment by jfsantos** [comment]
That is because the module Gammatone is not part of this package, but a dependency instead. Install it from github.com/detly/gammatone and you should be all set.

**Comment by gautambhat14** [comment]
> I am getting an error saying the Gammatone module is not present. I checked the package and the Gammatone module is not there. Can you please resolve this?

Thanks it works! will the score from Matlab differ from the one here?
