### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('Gammatone')

### ISSUE THREAD

**Issue by dmumtaz** [jfsantos/SRMRpy#4]
when I run the **python setup.py install**
the following error appears:

Searching for Gammatone
Reading https://pypi.org/simple/Gammatone/
Couldn't find index page for 'Gammatone' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for Gammatone
error: Could not find suitable distribution for Requirement.parse('Gammatone')

**Comment by jiaxp3144** [comment]
The needed 'Gammatone' can't be found in https://pypi.org/simple/. You may first install gammatone using https://github.com/detly/gammatone, and then install this package.
